language: objective-c
osx_image: xcode11.5
before_install:
  - gem install xcpretty
  - gem install xcpretty-travis-profiler-formatter
  - pip install --user -r requirements.txt
before_script:
  - make docs
script:
  - scripts/travis-build.sh build
  - scripts/travis-build.sh test
after_script:
  - make build/html
after_success:
  - bash <(curl -s https://codecov.io/bash) >$HOME/codecov.log 2>&1
after_failure:
  - tail -500 $HOME/build.log
  - tail -500 $HOME/test.log
  - grep "^Test Case.*).$" $HOME/test.log  | grep -v "' passed ("
notifications:
  irc:
    channels:
      - secure: "SpW6b7TF42r7kMiPFqnyX+gNdQSNAN/S38cezjwuu0bolIRE2it97TU8xJ0uhmLPyGI/YjUBM5OJNG5xcqXJhrBPCfN8TBqwyvWJ6/rfoDGT0WDHs69mLoIvCuUAXSxYWYQf560El6VX9oclkSReiZEGYdUMcUzwupCpMmcjUi4="
    template:
      - "%{author} @ %{repository} / %{branch} - Build:#%{build_number} : %{message} - Changes: %{compare_url} - Build details: %{build_url}"
addons:
  artifacts:
    s3_region: "eu-west-1"
    bucket: hammerspoontravisartifacts
    key:
      secure: "HJ4xnVX6PbU+H/baT2qEAzkAKi5H3LBTDgrYEGAJ77yxB6fJbyKz19Es+pCVsD1Bqv/cNS44MiVhL8oxGmLZovdCzZeDnir578qzUKiTNAfw2WoCOGmf8Jwp5gD726mCnpLtqefiHADK9VQ53p/0DxWMNAdPAqivG8G+fbd7D+Q="
    secret:
      secure: "DKxRobGmQWTxQeWNsDMWORe4FBBH8tdtlT43FTSX5/pIoJAfxBV18EHwliI2YRrxtm0kcpsZJ8rf7oeRgezPuKD2auu2CQIxVapVnOG8Lz6wEM8aHVq9OT4jbTusn1m/slKHKe8sjyJanH9thSxe3w1Q8evXzPdRUtnskXAs7Vg="
    paths:
      - $HOME/build.log
      - $HOME/test.log
    target_paths: logs/$TRAVIS_BUILD_NUMBER
